version: '3.1'

services:
  postgres:
    image: postgres:14
    container_name: postgres-innodom
    environment:
      POSTGRES_DB: ${DB_USER_POS}
      POSTGRES_USER: ${DB_PASSWORD_POS}
      POSTGRES_PASSWORD: ${DB_NAME_POS}
    ports:
      - "25565:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "innodom", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
