version: "3.8"

services:
  dev_db:
    image: postgres:latest
    container_name: postgres_dev
    environment:
      POSTGRES_USER: ${DB_USER_POS}
      POSTGRES_PASSWORD: ${DB_PASSWORD_POS}
      POSTGRES_DB: ${DB_NAME_POS}
    ports:
      - "54321:5432"
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER_POS} -h localhost -d ${DB_NAME_POS}"]
      start_period: 15s
      interval: 15s
      timeout: 5s
      retries: 3


volumes:
  dev_db_data:
