# Generated by Django 5.0.1 on 2024-01-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_comment_product_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(related_name='comment', to='product.comment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.ManyToManyField(related_name='rating', to='product.rating'),
        ),
    ]
